Repository deeplearningunb/stonks, pull requests merged in 2019-11, with the labels that each got.

#3 Set up issue and pull request templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#4 Fix issues templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: bug

#10 Creating MIT license
  LICENSE
Labels: documentation

#11 Issue 06 code of conduct
  .github/CODE_OF_CONDUCT.md
Labels: documentation

#12 Adding contributing guide
  .github/CONTRIBUTING.md
Labels: documentation

#15 Issue 13 move code of conduct and contributing
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: bug

#17 Code that extracts dataset
  src/extract_data.py
Labels: dataset, enhancement

#16 Updating readme informations
  README.md
  img/mario.gif
Labels: documentation

#26 Updating Dataset
  Dataset/Test/AMZN.csv
  Dataset/Test/NFLX.csv
  Dataset/Test/TSLA.csv
  Dataset/Training/AMZN.csv
  Dataset/Training/NFLX.csv
  Dataset/Training/TSLA.csv
Labels: bug, dataset

#32 Adding summary about RNNs
  README.md
Labels: documentation

#34 Issue 27 processing training dataset data
  src/stonks.py
Labels: data pre processing, dataset, enhancement

#38 Definition of predictors
  src/stonks.py
Labels: enhancement, keras

#39 Adding rnn
  src/stonks.py
Labels: enhancement, lstm

#40 Adding neural network training
  src/stonks.py
Labels: enhancement, keras

#35 Adding anaconda description
  ENVIRONMENT.md
  README.md
Labels: documentation

#36 Updating members informations
  README.md
Labels: documentation, enhancement

#37 Adding description to dataset
  README.md
Labels: documentation, enhancement
