Repository deeplearningunb/stonks, pull requests merged in 2019-12, with the labels that each got.

#41 Adding test to neural network
  src/stonks.py
Labels: enhancement

#43 Issue 42 update readme
  README.md
  img/graph.png
Labels: documentation

#45 Add notebook
  src/stonks.ipynb
Labels: enhancement

#48 Adding roadmap
  README.md
  img/roadmap.png
Labels: documentation, enhancement
